name: felipesanchez
favicon: null
layout_spectrum: 0.3203858977649361
typography_spectrum: 0.4422081089578569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.404581421520561
  lightness: 0.8589283735491335
  saturation: 0.1074619886931032
  rhythmicContrast: 0.7170697445981205
purpose: []
