name: felipesanchez
favicon: null
layout_spectrum: 0.3203858977649361
typography_spectrum: 0.4422081089578569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#000000'
    - '#3f3f3f'
    - '#828282'
    - '#bcbcbc'
  brandStrength: 0.5
  lightness: 0.8589283735491335
  saturation: 0.1074619886931032
  rhythmicContrast: 0.7170697445981205
purpose: []
